---
title: "burn-temps"
format: html
editor: visual
---

# set-up

## reading in packages and data

```{r}
#| message: false
# general use
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(car)
library(effectsize)
library(rstatix)

burn_temps <- read_xlsx(path = here("data", 
                        "Burn Temps.xlsx"))

fuel_depth <- read_xlsx(path = here("data",
                          "fuel depth.xlsx"))
```

## block and temperature

```{r}
burn_temps_block <- burn_temps %>% clean_names() %>% 
  rename(distance = distance_from_edge_m,
         block = edge,
         tag_depth = depth) %>% 
  mutate(block = case_when(
             block == "east" ~ "No Seed",
             block == "west" ~ "No Seed",
             block == "north" ~ "Low Seed",
             block == "south" ~ "High Seed")) %>% 
  filter(tag_depth == "sub-surface") %>% 
  mutate(block = fct_relevel(block, "No Seed", "Low Seed", "High Seed"))

ggplot(data = burn_temps_block,
       aes(x = block,
           y = max_temp,
           color = block)) +
  geom_boxplot() +
  theme_minimal()
```

## block and & depth and temp

```{r}
fuel_depth_clean <- fuel_depth %>% clean_names() %>% 
  rename(block = edge,
         distance = meters_from_edge,
         fuel_depth = depth) %>% 
  select(block, distance, fuel_depth) %>% 
  mutate(block = case_when(
             block == "east" ~ "No Seed",
             block == "west" ~ "No Seed",
             block == "north" ~ "Low Seed",
             block == "south" ~ "High Seed")) %>% 
  mutate(block = fct_relevel(block, "No Seed", "Low Seed", "High Seed"))

fuel_burn_temp <- merge(fuel_depth_clean, burn_temps_block, by=c("block","distance"))

ggplot(fuel_burn_temp,
       aes(x = block,
           y = fuel_depth,
           color = block)) +
  geom_boxplot() +
  theme_minimal()

ggplot(fuel_burn_temp,
       aes(x = fuel_depth,
           y = max_temp)) +
  geom_point() +
  theme_minimal()
```

## temp & density

```{r}
veg_data <- read_xlsx(path = here("data", 
                        "post_treatment_veg_all.xlsx"),
                         sheet = "CCBER_VegMonitoring_Quadrat_4")

veg_data_clean <- veg_data %>% 
  clean_names() %>% 
  select(global_id, monitoring_date, unlisted_lagoon_transect_name_number, transect_distance_of_quadrat, count_of_native_species, sum_of_native_cover, sum_of_non_native_cover, count_of_non_native_species, sum_of_unknown_cover, sum_of_thatch, bare_ground, sum_of_all_cover) %>% 
  rename(treatment = unlisted_lagoon_transect_name_number,
         native_count = count_of_native_species,
         native_cover = sum_of_native_cover,
         nonnative_count = count_of_non_native_species,
         nonnative_cover = sum_of_non_native_cover,
         thatch_cover = sum_of_thatch) %>% 
  mutate(total_cover = sum_of_all_cover - sum_of_unknown_cover) %>% 
  mutate(weeding = case_when(
             treatment == "Thatch-None" ~ "Thatch Removal",
             treatment == "Thatch-Low" ~ "Thatch Removal",
             treatment == "Thatch-High" ~ "Thatch Removal",
             treatment == "Control-None" ~ "Control",
             treatment == "Control-Low" ~ "Control",
             treatment == "Control-High" ~ "Control",
             treatment == "Burn-None" ~ "Burn",
             treatment == "Burn-Low" ~ "Burn",
             treatment == "Burn-High" ~ "Burn",
             treatment == "Clethodim-None" ~ "Herbicide",
             treatment == "Clethodim-Low" ~ "Herbicide",
             treatment == "Clethodim-High" ~ "Herbicide"),
         seeding = case_when(
             treatment == "Thatch-None" ~ "None",
             treatment == "Thatch-Low" ~ "Low",
             treatment == "Thatch-High" ~ "High",
             treatment == "Control-None" ~ "None",
             treatment == "Control-Low" ~ "Low",
             treatment == "Control-High" ~ "High",
             treatment == "Burn-None" ~ "No Seed",
             treatment == "Burn-Low" ~ "Low Seed",
             treatment == "Burn-High" ~ "High Seed",
             treatment == "Clethodim-None" ~ "None",
             treatment == "Clethodim-Low" ~ "Low",
             treatment == "Clethodim-High" ~ "High")) %>% 
  filter(weeding == "Burn")


```

## burn temp by depth & dist

```{r}
# cleaning up data
burn_temps_clean <- burn_temps %>% clean_names() %>%
  rename(distance = distance_from_edge_m)

burn_temps_avg <- burn_temps_clean %>%
  group_by(edge, depth) %>% 
  reframe(mean = mean(max_temp)) %>% 
  mutate(depth = fct_relevel(depth, "surface", "sub-surface"))

ggplot(data = burn_temps_avg,
       aes(x = edge,
           y = mean,
           color = depth)) +
  geom_point(size = 3) +
  ylim(0,350) +
  theme_minimal() +
  scale_color_manual(values = c("#c61a09", "#8ac926")) +
  labs(x = "Edge",
        y = "Temperature (C)",
        color = "Depth",
        title = "Average Fire Temperature Each Side")
```
