---
title: "thatch-veg"
format: html
editor: visual
---

## reading in packages and data

```{r}
#| message: false
# general use
library(tidyverse)
library(readxl)
library(here)
library(janitor)

# visualizing pairs
library(GGally)

# model selection
library(MuMIn)

# model predictions
library(ggeffects)

# model tables
library(gtsummary)
library(flextable)
library(modelsummary)
```

## cleaning data

```{r}
thatch_veg <- read_xlsx(path = here("data", 
                        "thatch.xlsx"),
                         sheet = "thatch_percent_cover") %>% 
  clean_names() %>% 
  rename(subplot = unlisted_lagoon_transect_name_number) %>% 
  select(subplot, sum_of_native_cover, sum_of_non_native_cover, sum_of_thatch, bare_ground) %>% 
 pivot_longer(cols = c(sum_of_native_cover, sum_of_non_native_cover, sum_of_thatch, bare_ground)) %>% 
  rename(percent_cover = value,
         veg_type = name) %>% 
  group_by(subplot, veg_type) %>% 
 mutate(veg_type = case_when(
    veg_type == "sum_of_native_cover" ~ "Native",
    veg_type == "sum_of_non_native_cover" ~ "Non-Native",
    veg_type == "sum_of_thatch" ~ "Thatch",
    veg_type == "bare_ground" ~ "Bare Ground"),
    subplot = case_when(
      subplot == "Thatch High" ~ "High Seed Rate",
      subplot == "Thatch Low" ~ "Low Seed Rate",
      subplot == "Thatch No" ~ "No Seed"))

thatch_veg_avg <- thatch_veg %>% 
  reframe(mean = mean(percent_cover)) %>% 
  mutate(veg_type = fct_relevel(veg_type, "Native", "Non-Native", "Thatch", "Bare Ground"))
```

## bar chart

```{r}
ggplot(data = thatch_veg_avg,
       aes(x = subplot,
           y = mean,
           fill = veg_type)) +
       geom_bar(stat = "identity",
                position = position_dodge()) +
  theme_minimal() + 
  scale_fill_manual(values = c("#8ac926", "#c61a09", "#fce205", "#5097a4")) +
   labs(x = "Seeding Treatment",
        y = "Percent Cover",
        fill = "Vegetation",
        title = "Thatch Removal Pre-Seeding Vegetation Cover") +
  ylim(0,100)
```