---
title: "Thesis Figures"
format: html
editor: visual
---
# Packages
```{r}
#| message: false
# general use
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(car)
library(effectsize)
library(rstatix)
library(multcomp)
```

# Data Reading
```{r}
veg_data <- read_xlsx(path = here("data", 
                        "post_treatment_veg_all.xlsx"),
                         sheet = "CCBER_VegMonitoring_Quadrat_4")

burn_temps <- read_xlsx(path = here("data", 
                        "Burn Temps.xlsx"))

fuel_depth <- read_xlsx(path = here("data",
                          "fuel depth.xlsx"))

density_seeded <- read_xlsx(path = here("data", 
                        "density_count veg data.xlsx"))

subplot_area <- read_xlsx(path = here("data", 
                        "subplot size.xlsx"),
                        sheet = "Sheet2")
```

# Cleaning
```{r}
veg_data_clean <- veg_data %>% 
  clean_names() %>% 
dplyr::select(global_id, monitoring_date, unlisted_lagoon_transect_name_number, transect_distance_of_quadrat, count_of_native_species, sum_of_native_cover, sum_of_non_native_cover, count_of_non_native_species, sum_of_unknown_cover, sum_of_thatch, bare_ground, sum_of_all_cover) %>% 
  rename(treatment = unlisted_lagoon_transect_name_number,
         native_count = count_of_native_species,
         native_cover = sum_of_native_cover,
         nonnative_count = count_of_non_native_species,
         nonnative_cover = sum_of_non_native_cover,
         thatch_cover = sum_of_thatch) %>% 
  mutate(total_cover = sum_of_all_cover - sum_of_unknown_cover) %>% 
  mutate(weeding = case_when(
             treatment == "Thatch-None" ~ "Thatch Removal",
             treatment == "Thatch-Low" ~ "Thatch Removal",
             treatment == "Thatch-High" ~ "Thatch Removal",
             treatment == "Control-None" ~ "Control",
             treatment == "Control-Low" ~ "Control",
             treatment == "Control-High" ~ "Control",
             treatment == "Burn-None" ~ "Burn",
             treatment == "Burn-Low" ~ "Burn",
             treatment == "Burn-High" ~ "Burn",
             treatment == "Clethodim-None" ~ "Herbicide",
             treatment == "Clethodim-Low" ~ "Herbicide",
             treatment == "Clethodim-High" ~ "Herbicide"),
         seeding = case_when(
             treatment == "Thatch-None" ~ "None",
             treatment == "Thatch-Low" ~ "Low",
             treatment == "Thatch-High" ~ "High",
             treatment == "Control-None" ~ "None",
             treatment == "Control-Low" ~ "Low",
             treatment == "Control-High" ~ "High",
             treatment == "Burn-None" ~ "None",
             treatment == "Burn-Low" ~ "Low",
             treatment == "Burn-High" ~ "High",
             treatment == "Clethodim-None" ~ "None",
             treatment == "Clethodim-Low" ~ "Low",
             treatment == "Clethodim-High" ~ "High")) %>% 
  mutate(weeding= fct_relevel(weeding, "Control", "Thatch Removal", "Herbicide", "Burn"),
         seeding = fct_relevel(seeding, "None", "Low", "High"))

density_seeded_clean <- density_seeded %>% 
  group_by(species, weeding, seeding)

subplot_area_clean <- subplot_area %>% clean_names() %>%  group_by(weeding, seeding) %>% filter(! seeding =="none") %>% 
  mutate(weeding = case_when(
             weeding == "thatch removal" ~ "Thatch Removal",
             weeding == "herbicide" ~ "Herbicide",
             weeding == "burn" ~ "Burn",
             weeding == "control" ~ "Control"))
```

# ANOVAS
## Thatch Cover 
```{r}
hist(veg_data_clean $ thatch_cover)
## bimodal, doing Kruskal-Wallis

kruskal.test(thatch_cover ~ weeding,
             data = veg_data_clean)
## chi-squared 73.12, df = 3, p > 0.001

dunn_test(thatch_cover ~ weeding, 
          data = veg_data_clean)
## all pairwise combinations are significant except for thatch-removal and control, which have similar thatch cover post-treatment. [blank]-burn statistics are all negative, with herbicide and burn being largest difference, and thatch removal and control being fairly similar. For herbicide, both control and thatch removal have similar statistics, meaning that they have a similar difference in thatch cover ti herbicide.

kruskal_effsize(thatch_cover ~ weeding, 
          data = veg_data_clean)
## large effect size 

# plot
ggplot(veg_data_clean) +
  aes(x = weeding, y = thatch_cover, color = weeding) +
  geom_boxplot() +
 geom_point(position=position_jitterdodge(
   jitter.width = 0,
   jitter.height = 0,
    seed = NULL),
            alpha = 0.3) +
  theme_minimal() +
  ylim(0,100) +
  scale_color_manual(values = c("#38A800", "#FF327C", "#00A9E6", "#F77600")) 
 # labs(x = "Treatment",
     #  y = "Cover (%)",
      # color = "Treatment")
       #title = "Non-Native Density by Weeding Treatment") 
```

## Native Cover
```{r}
hist(veg_data_clean $ native_cover)

nativecover_aov <- aov(sqrt(native_cover) ~ weeding * seeding, data = veg_data_clean)

summary(nativecover_aov)

plot(nativecover_aov)

cooksnativeaov <- cooks.distance(nativecover_aov)

plot(cooksnativeaov)
## all looking fairly normal! make sure to note that i took square root of native cover

leveneTest(sqrt(native_cover) ~ weeding * seeding, veg_data_clean)
## variances not sig, yay!

TukeyHSD(nativecover_aov)
## post-hoc slay, elab on pairwise combinations

effectsize::eta_squared(nativecover_aov)
# effect size is large for weeding effect, not seeding

# plot
ggplot(veg_data_clean) +
  aes(x = weeding, y = native_cover, color = seeding) +
  geom_boxplot() +
 geom_point(position=position_jitterdodge(
   jitter.width = 0,
   jitter.height = 0,
    seed = NULL),
            alpha = 0.3) +
  theme_minimal() +
  scale_color_manual(values = c("#FFC567", "#67C0AC", "#B660CD")) 
  #labs(x = "Weeding Treatment",
       #y = "Count",
       #color = "Seeding Rate",
       #title = "Native Density by Weeding and Seeding Treatments")

```

## Non-native Cover

## CAME Cover

## PHDI Cover

## CLPU Cover

## CAME Success

## PHDI Success

## CLPU Success

## total count of species per species & thatch cover

## total native cover per came clpu and phdi
